#root_dir: C:\Users\rcook\Music
root_dir: /Users/richard.cook/Documents/Tunes
#root_dir: D:\MUSIC FOLDER
skips:
  - .DS_Store
  - .ini
  - .jpg
fixups:
  - album_id: db113956-3fc2-4153-953c-443a29a3410b
    dir: Days_of_the_New_I_Yellow
    album_title_tag_override: Days of the New I (Yellow)
  - album_id: 8f145aa3-f649-486e-9610-2d27f7c289b4
    dir: Days_of_the_New_II_Green
    album_title_tag_override: Days of the New II (Green)
  - album_id: 819e59a9-1e55-4407-9006-4aaaf4a8521f
    dir: Days_of_the_New_III_Red
    album_title_tag_override: Days of the New III (Red)
  - album_id: 004a9421-65cc-4683-bc2b-e617a9f9e6bd
    dir: Best_of_the_Beast_Limited_Edition
    album_title_tag_override: Best of the Beast (Limited Edition)
  - album_id: fdd6cf5c-0d1a-4743-846c-498dd513e6c9
    dir: Best_of_the_Beast_Standard_Edition
    album_title_tag_override: Best of the Beast (Standard Edition)
